accounts:
  - name: testvalidator
    coins: ["100000000stake"]
  - name: community
    coins: ["10000000000token"]
  - name: ecosystem
    coins: ["20000000000token"]
  - name: reserve
    coins: ["20000000000token"]
  - name: launch
    coins: ["10000000000token"]
